LegoAgent-Eve: Recognition Class Reference
Recognition Class Reference
Public Member Functions
Recognition ()
Figure recognizeSVM ()
Erkennung einer Figur - Hauptfunktion Beinhaltet.
Figure recognizeKNN ()
Erkennung einer Figur - Hauptfunktion Beinhaltet.
void removeAll ()
Loescht alle bisherigen Daten inklusive Trainingsdaten, gescannte Bilder, etc.
void train (Figure figure)
Funktion lernt einen neuen Datenpunkt als reine Wahrheit.
Private Attributes
IScanner scanner
SVM svm
NearestNeighbour knn
Dataset dataset
Constructor & Destructor Documentation
Recognition ()
References Dataset.load().
Member Function Documentation
Figure recognizeKNN ()
Erkennung einer Figur - Hauptfunktion Beinhaltet.
Scannen des Bildes
Vorbereiten der SVM, wenn erforderlich
Bestimmen des Bildes mit dem K Nearest Neighbour- Algorithmus
Returns
: Figure Gibt die berechnete Figur zurueck
Implements IRecognition.
References NearestNeighbour.classify(), Logger.log(), and IScanner.scanNewDataPoint().
Referenced by GUI.processMenu().
Figure recognizeSVM ()
Erkennung einer Figur - Hauptfunktion Beinhaltet.
Scannen des Bildes
Vorbereiten der SVM, wenn erforderlich
Bestimmen des Bildes mit der SVM
Returns
Figure Gibt die berechnete Figur zurueck
Implements IRecognition.
References SVM.classify(), Logger.log(), and IScanner.scanNewDataPoint().
Referenced by GUI.processMenu().
void removeAll ()
Loescht alle bisherigen Daten inklusive Trainingsdaten, gescannte Bilder, etc.
Implements IRecognition.
References Dataset.clearAll(), Logger.log(), and Dataset.store().
Referenced by GUI.processMenu().
void train (Figure figure)
Funktion lernt einen neuen Datenpunkt als reine Wahrheit.
Implements IRecognition.
References Dataset.addNewData(), SVM.findSupportVectors(), Logger.log(), IScanner.scanNewDataPoint(), IDataPoint.setFigure(), and Dataset.store().
Referenced by GUI.processMenu().
Member Data Documentation
Dataset dataset private
NearestNeighbour knn private
IScanner scanner private
SVM svm private
The documentation for this class was generated from the following file:
leImRo/src/leImRo/Recognition.java