LegoAgent-Eve: NearestNeighbour Class Reference
NearestNeighbour Class Reference
Klasse zur Erkennung des Figurtyps mithilfe des k-NearestNeighbour Verfahrens.
Public Member Functions
NearestNeighbour (Dataset dataset)
Constructor.
NearestNeighbour (Dataset dataset, int kNeighbours)
Constructor.
void SetKNeighbours (int kNeighbour)
Set amount of selected nearest neighbour.
Figure classify (IDataPoint dataPoint)
Classify new Figure with k- Nearest Neighbour Algorithmn.
Private Member Functions
double calcEuklidDistance (IDataPoint actDataPoint, IDataPoint actPointToCompare)
Calc euclidean distance between two Figures.
boolean validateAmountOfTrainingData ()
Check amount of Trainingsdata to config k- Parameter.
Private Attributes
Dataset dataSet
int kNeighbours = 0
Detailed Description
Klasse zur Erkennung des Figurtyps mithilfe des k-NearestNeighbour Verfahrens.
Constructor & Destructor Documentation
NearestNeighbour (Dataset dataset)
Constructor.
Parameters
dataset Set dataset of classified Figures
NearestNeighbour (Dataset dataset, int kNeighbours)
Constructor.
Parameters
dataset Set dataset of classified Figures
kNeighbours Amount of selected nearest neighbours
References NearestNeighbour.kNeighbours.
Member Function Documentation
double calcEuklidDistance (IDataPoint actDataPoint, IDataPoint actPointToCompare) private
Calc euclidean distance between two Figures.
Parameters
actDataPoint
actPointToCompare
Returns
euclidean Distance between this Figures
References IDataPoint.getArea(), and IDataPoint.getPerimeter().
Referenced by NearestNeighbour.classify().
Figure classify (IDataPoint dataPoint)
Classify new Figure with k- Nearest Neighbour Algorithmn.
Parameters
dataPoint Figure to classify
Implements INearestNeighbour.
References NearestNeighbour.calcEuklidDistance(), Figure.circle, Dataset.getAllData(), NearestNeighbour.kNeighbours, Logger.log(), Figure.rectangle, IDataPoint.setFigure(), Figure.UNKNOWN, and NearestNeighbour.validateAmountOfTrainingData().
Referenced by Recognition.recognizeKNN().
void SetKNeighbours (int kNeighbour)
Set amount of selected nearest neighbour.
Parameters
Implements INearestNeighbour.
boolean validateAmountOfTrainingData () private
Check amount of Trainingsdata to config k- Parameter.
If no k available, the algorithmn use 50% of trainingsdata (odd figure)
Returns
References Dataset.getAllData(), NearestNeighbour.kNeighbours, and Logger.log().
Referenced by NearestNeighbour.classify().
Member Data Documentation
Dataset dataSet private
int kNeighbours = 0 private
Referenced by NearestNeighbour.classify(), NearestNeighbour.NearestNeighbour(), and NearestNeighbour.validateAmountOfTrainingData().
The documentation for this class was generated from the following file:
leImRo/src/leImRo/NearestNeighbour.java