LegoAgent-Eve: Vector Class Reference
Vector Class Reference
Hilfsklasse fuer SVM Implementierung Stellt Vector und Rechenmethoden fuer Vectoren zur Verfuegung.
Public Member Functions
Vector (double x, double y)
double getX ()
double getY ()
Vector multiply (double a)
String toString ()
Static Public Member Functions
static Vector subtract (Vector a, Vector b)
static Vector add (Vector a, Vector b)
static Vector getOrthogonal (Vector toInvert)
static double[] linearcombination (Vector vector1, Vector vector2, Vector destination)
Berechne Linearkombination von vektorA und vectorB zu vectorC a * vectorA + b * vectorB = vectorC.
Private Attributes
double x
double y
Detailed Description
Hilfsklasse fuer SVM Implementierung Stellt Vector und Rechenmethoden fuer Vectoren zur Verfuegung.
Constructor & Destructor Documentation
Vector (double x, double y)
References Vector.x, and Vector.y.
Referenced by Vector.add(), Vector.getOrthogonal(), Vector.multiply(), and Vector.subtract().
Member Function Documentation
static Vector add (Vector a, Vector b) static
References Vector.getX(), Vector.getY(), and Vector.Vector().
Referenced by SVM.computeSeparator().
static Vector getOrthogonal (Vector toInvert) static
References Vector.getX(), Vector.getY(), and Vector.Vector().
Referenced by SVM.computeSeparator().
double getX ()
References Vector.x.
Referenced by Vector.add(), Vector.getOrthogonal(), Vector.linearcombination(), Vector.subtract(), and Vector.toString().
double getY ()
References Vector.y.
Referenced by Vector.add(), Vector.getOrthogonal(), Vector.linearcombination(), Vector.subtract(), and Vector.toString().
static double [] linearcombination (Vector vector1, Vector vector2, Vector destination) static
Berechne Linearkombination von vektorA und vectorB zu vectorC a * vectorA + b * vectorB = vectorC.
Mit Mathe-Magie ergibt sich:
        x3
y3 -  ------  *  y2
        x2
a = ------------------— x1 y1 - ---— * y2 x2
und
 x3 - a  * x1
b = ---------------— x2
returns double{a, b}
References Vector.getX(), and Vector.getY().
Referenced by SVM.classify(), and SVM.computeSeparator().
Vector multiply (double a)
References Vector.Vector().
Referenced by SVM.computeSeparator().
static Vector subtract (Vector a, Vector b) static
References Vector.getX(), Vector.getY(), and Vector.Vector().
Referenced by SVM.classify(), and SVM.computeSeparator().
String toString ()
References Vector.getX(), and Vector.getY().
Member Data Documentation
double x private
Referenced by Vector.getX(), and Vector.Vector().
double y private
Referenced by Vector.getY(), and Vector.Vector().
The documentation for this class was generated from the following file:
leImRo/src/leImRo/Vector.java