LegoAgent-Eve: Scanner Class Reference
Scanner Class Reference
Public Member Functions
Scanner ()
IDataPoint scanNewDataPoint ()
scan whole image and calculate the characteristics of the objects
Static Public Attributes
static final int resolution = 4
static final int yMax = 946
static final int xSpeed = 200
static final int xAcceleration = 200
static final int ySpeed = 500
static final int yAcceleration = 500
static final int minYAngle = 22
static final int minXAngle = 5
static final int startYDir = -1
static final int startXDir = -1
static final int sensorSamples = 5
static final double rgbThreshold = 0.12
Private Member Functions
int[][] readImage ()
scan the whole picture.
int getPixelColor ()
read in sensor value and filter it
int getYIndex (int i)
calculates the y Index for the image buffer Depending on the direction the index must be calculated different because of the meander shape of scanning
void turnXMotor (int xAnglePerPixel)
turn the XMotor about given angle
void turnYMotor (int yAnglePerPixel)
turn the YMotor about given angle
void returnToHome (int xAnglePerPixel, int yAnglePerPixel)
return to the origin position after scanning image
void invertDirection ()
invert the direction flag 1 means rotate clockwise -1 means rotate counter-clockwise
String debugImage (int[][] Image)
print Image as String as Debug String
void printImageOnLCD (int[][] image)
IDataPoint calculateCharacteristics (int[][] image)
calculate the characteristics perimeter (sqared) and area of a given image
Private Attributes
int pixel
int dir
RegulatedMotor XMotor
RegulatedMotor YMotor
EV3ColorSensor Sensor
SampleProvider RgbSample
SampleProvider RgbFilter
Constructor & Destructor Documentation
Scanner ()
References Scanner.startYDir.
Member Function Documentation
IDataPoint calculateCharacteristics (int image[][]) private
calculate the characteristics perimeter (sqared) and area of a given image
Parameters
image int buffer of the image
Returns
DataPoint with the characteristics perimeter and area
References Logger.log(), and Scanner.pixel.
Referenced by Scanner.scanNewDataPoint().
String debugImage (int Image[][]) private
print Image as String as Debug String
References Scanner.pixel.
Referenced by Scanner.readImage().
int getPixelColor () private
read in sensor value and filter it
Returns
0 for white 1 for black
References Logger.log(), and Scanner.sensorSamples.
Referenced by Scanner.readImage().
int getYIndex (int i) private
calculates the y Index for the image buffer Depending on the direction the index must be calculated different because of the meander shape of scanning
Parameters
i current position y Motor
Returns
index for the image buffer
Referenced by Scanner.readImage().
void invertDirection () private
invert the direction flag 1 means rotate clockwise -1 means rotate counter-clockwise
Referenced by Scanner.readImage().
void printImageOnLCD (int image[][]) private
References Scanner.pixel.
Referenced by Scanner.readImage().
int [][] readImage () private
scan the whole picture.
This is done in a meander shape. See the following illustration (s is a scan, -> symbolize movement): s->s->s->s \/ s<-s<-s<-s \/ s->s->s->s \/ s<-s<-s<-s
This shows that for the reading of a line are one scan more is necessary than movements.
References Scanner.debugImage(), Scanner.getPixelColor(), Scanner.getYIndex(), Scanner.invertDirection(), Logger.log(), Scanner.pixel, Scanner.printImageOnLCD(), Scanner.resolution, Scanner.returnToHome(), Scanner.turnXMotor(), and Scanner.turnYMotor().
Referenced by Scanner.scanNewDataPoint().
void returnToHome (int xAnglePerPixel, int yAnglePerPixel) private
return to the origin position after scanning image
References Scanner.startYDir.
Referenced by Scanner.readImage().
IDataPoint scanNewDataPoint ()
scan whole image and calculate the characteristics of the objects
Implements IScanner.
References Scanner.calculateCharacteristics(), and Scanner.readImage().
void turnXMotor (int xAnglePerPixel) private
turn the XMotor about given angle
Parameters
xAnglePerPixel angle to rotate
References Logger.log().
Referenced by Scanner.readImage().
void turnYMotor (int yAnglePerPixel) private
turn the YMotor about given angle
Parameters
yAnglePerPixel angle to rotate
References Logger.log().
Referenced by Scanner.readImage().
Member Data Documentation
int dir private
final int minXAngle = 5 static
final int minYAngle = 22 static
int pixel private
Referenced by Scanner.calculateCharacteristics(), Scanner.debugImage(), Scanner.printImageOnLCD(), and Scanner.readImage().
final int resolution = 4 static
Referenced by Scanner.readImage().
SampleProvider RgbFilter private
SampleProvider RgbSample private
final double rgbThreshold = 0.12 static
EV3ColorSensor Sensor private
final int sensorSamples = 5 static
Referenced by Scanner.getPixelColor().
final int startXDir = -1 static
final int startYDir = -1 static
Referenced by Scanner.returnToHome(), and Scanner.Scanner().
final int xAcceleration = 200 static
RegulatedMotor XMotor private
final int xSpeed = 200 static
final int yAcceleration = 500 static
final int yMax = 946 static
RegulatedMotor YMotor private
final int ySpeed = 500 static
The documentation for this class was generated from the following file:
leImRo/src/leImRo/Scanner.java