LegoAgent-Eve: Logger Class Reference
Logger Class Reference
Static Public Member Functions
static void log (String str)
Static Public Attributes
static final String fileLocation = "logger.txt"
Static Private Attributes
static FileWriter fw
static BufferedWriter bw
Member Function Documentation
static void log (String str) static
Referenced by Dataset.addNewData(), Scanner.calculateCharacteristics(), NearestNeighbour.classify(), SVM.classify(), SVM.computeSeparator(), SVM.findSupportVectors(), Scanner.getPixelColor(), Dataset.load(), Scanner.readImage(), Recognition.recognizeKNN(), Recognition.recognizeSVM(), Recognition.removeAll(), Dataset.store(), Recognition.train(), Scanner.turnXMotor(), Scanner.turnYMotor(), and NearestNeighbour.validateAmountOfTrainingData().
Member Data Documentation
BufferedWriter bw static private
final String fileLocation = "logger.txt" static
FileWriter fw static private
The documentation for this class was generated from the following file:
leImRo/src/leImRo/Logger.java