LegoAgent-Eve: Dataset Class Reference
Dataset Class Reference
Public Member Functions
Dataset ()
void setsVMPoints (IDataPoint[] sVMPoints)
TODO: Sort the received array by figure Type ()
int getSvmOrientation ()
void setSvmOrientation (int svmOrientation)
void clearAll ()
removes the currently existing dataset, does not store this changes to disk.
void addNewData (IDataPoint data)
Adds a new data to the dataset in RAM, does not store this changes to disk.
ArrayList< IDataPoint > getAllData ()
returns the current dataset from RAM.
IDataPoint[] getSVMPoints ()
returns the current SVM-Points to create the border, or null, if no data is stored
String toString ()
returns the String-Repräsentation of this object
void removeStoredSVMPoints ()
removes the currently stored SVM-Points.
Static Public Member Functions
static void store (Dataset dataset)
stores the current status of the dataset to the disk.
static Dataset load ()
loads the data that are currently stored in the filesystem.
Static Public Attributes
static final String csvSplit = ","
Private Attributes
ArrayList< IDataPoint > dataset
IDataPoint[] sVMPoints
int svmOrientation = 0
orientation, whether negative values means circles or rectangles 0: circles get negative values, 1: rectangles get negative values
Static Private Attributes
static final String fileLocation = "datapoints.csv"
the path and filename in the filesystem of the serialized data.
Constructor & Destructor Documentation
Dataset ()
Referenced by Dataset.load().
Member Function Documentation
void addNewData (IDataPoint data)
Adds a new data to the dataset in RAM, does not store this changes to disk.
Implements IDataset.
References Logger.log().
Referenced by Dataset.load(), and Recognition.train().
void clearAll ()
removes the currently existing dataset, does not store this changes to disk.
Implements IDataset.
References Dataset.removeStoredSVMPoints().
Referenced by Recognition.removeAll().
ArrayList<IDataPoint> getAllData ()
returns the current dataset from RAM.
Implements IDataset.
References Dataset.dataset.
Referenced by NearestNeighbour.classify(), SVM.findSupportVectors(), Dataset.store(), and NearestNeighbour.validateAmountOfTrainingData().
int getSvmOrientation ()
References Dataset.svmOrientation.
Referenced by SVM.classify(), and SVM.findSupportVectors().
IDataPoint [] getSVMPoints ()
returns the current SVM-Points to create the border, or null, if no data is stored
Implements IDataset.
References Dataset.sVMPoints.
Referenced by SVM.computeSeparator().
static Dataset load () static
loads the data that are currently stored in the filesystem.
Path is specified by static variable fileLocation. TODO: Load of SVMPoints from separate file
References Dataset.addNewData(), Figure.circle, Dataset.csvSplit, Dataset.dataset, Dataset.Dataset(), Dataset.fileLocation, Logger.log(), and Figure.rectangle.
Referenced by Recognition.Recognition().
void removeStoredSVMPoints ()
removes the currently stored SVM-Points.
Used e.g. in case of addition of a new datapoint to the dataset.
Implements IDataset.
Referenced by Dataset.clearAll().
void setSvmOrientation (int svmOrientation)
References Dataset.svmOrientation.
Referenced by SVM.findSupportVectors().
void setsVMPoints (IDataPoint[] sVMPoints)
TODO: Sort the received array by figure Type ()
Parameters
sVMPoints
References Dataset.sVMPoints.
Referenced by SVM.findSupportVectors().
static void store (Dataset dataset) static
stores the current status of the dataset to the disk.
Storage-path is specified by static variable fileLocation.
References Dataset.csvSplit, Dataset.fileLocation, Dataset.getAllData(), and Logger.log().
Referenced by Recognition.removeAll(), and Recognition.train().
String toString ()
returns the String-Repräsentation of this object
Member Data Documentation
final String csvSplit = "," static
Referenced by Dataset.load(), and Dataset.store().
ArrayList<IDataPoint> dataset private
Referenced by Dataset.getAllData(), and Dataset.load().
final String fileLocation = "datapoints.csv" static private
the path and filename in the filesystem of the serialized data.
Referenced by Dataset.load(), and Dataset.store().
int svmOrientation = 0 private
orientation, whether negative values means circles or rectangles 0: circles get negative values, 1: rectangles get negative values
Referenced by Dataset.getSvmOrientation(), and Dataset.setSvmOrientation().
IDataPoint [] sVMPoints private
Referenced by Dataset.getSVMPoints(), and Dataset.setsVMPoints().
The documentation for this class was generated from the following file:
leImRo/src/leImRo/Dataset.java