LegoAgent-Eve: DataPoint Class Reference
DataPoint Class Reference
Basisklasse zur Beschreibung eines Datensatzes (ein gescanntes Bildes) mit den benoetigten Werten zur Erkennung.
Public Member Functions
DataPoint (int perimeter, int area)
DataPoint (int perimeter, int area, Figure figure)
int getPerimeter ()
Returns the perimeter of this data.
int getArea ()
returns the area of this data.
Figure getFigure ()
returns the type of figure of this data, if set.
void setFigure (Figure f)
set Figure of DataPoint.
String toString ()
Liefert die String-Repräsentation des Datenpunkts zurück.
Vector toVector ()
Private Attributes
int perimeter
periemeter and area of this data
Figure figure
Type of figure.
Detailed Description
Basisklasse zur Beschreibung eines Datensatzes (ein gescanntes Bildes) mit den benoetigten Werten zur Erkennung.
Constructor & Destructor Documentation
DataPoint (int perimeter, int area)
References DataPoint.perimeter, and Figure.UNKNOWN.
DataPoint (int perimeter, int area, Figure figure)
References DataPoint.figure, and DataPoint.perimeter.
Member Function Documentation
int getArea ()
returns the area of this data.
Implements IDataPoint.
Referenced by DataPoint.toString().
Figure getFigure ()
returns the type of figure of this data, if set.
By constructor, if no figure is specified, Figure.UNKNOWN is set as value
Implements IDataPoint.
References DataPoint.figure.
Referenced by DataPoint.toString().
int getPerimeter ()
Returns the perimeter of this data.
Implements IDataPoint.
References DataPoint.perimeter.
Referenced by DataPoint.toString().
void setFigure (Figure f)
set Figure of DataPoint.
Only possible if figure = UNKNOWN
Implements IDataPoint.
References Figure.UNKNOWN.
String toString ()
Liefert die String-Repräsentation des Datenpunkts zurück.
References DataPoint.getArea(), DataPoint.getFigure(), and DataPoint.getPerimeter().
Vector toVector ()
Implements IDataPoint.
Member Data Documentation
Figure figure private
Type of figure.
Referenced by DataPoint.DataPoint(), and DataPoint.getFigure().
int perimeter private
periemeter and area of this data
Referenced by DataPoint.DataPoint(), and DataPoint.getPerimeter().
The documentation for this class was generated from the following file:
leImRo/src/leImRo/DataPoint.java