LegoAgent-Eve: Figure Enum Reference
Figure Enum Reference
Enumeration der bestehenden Figur-Arten.
Public Member Functions
String toString ()
Public Attributes
UNKNOWN =("???")
circle =("O")
rectangle =("[]")
Private Member Functions
Figure (String value)
Private Attributes
final String description
Detailed Description
Enumeration der bestehenden Figur-Arten.
Constructor & Destructor Documentation
Figure (String value) private
Member Function Documentation
String toString ()
Member Data Documentation
circle =("O")
Referenced by NearestNeighbour.classify(), SVM.classify(), Dataset.load(), and GUI.processMenu().
final String description private
rectangle =("[]")
Referenced by NearestNeighbour.classify(), SVM.classify(), Dataset.load(), and GUI.processMenu().
UNKNOWN =("???")
Referenced by NearestNeighbour.classify(), SVM.classify(), DataPoint.DataPoint(), and DataPoint.setFigure().
The documentation for this enum was generated from the following file:
leImRo/src/leImRo/Figure.java