LegoAgent-Eve: IDataPoint Interface Reference
IDataPoint Interface Reference
Public Member Functions
int getPerimeter ()
int getArea ()
Figure getFigure ()
void setFigure (Figure f)
Vector toVector ()
Member Function Documentation
int getArea ()
Implemented in DataPoint.
Referenced by NearestNeighbour.calcEuklidDistance().
Figure getFigure ()
Implemented in DataPoint.
int getPerimeter ()
Implemented in DataPoint.
Referenced by NearestNeighbour.calcEuklidDistance().
void setFigure (Figure f)
Implemented in DataPoint.
Referenced by NearestNeighbour.classify(), and Recognition.train().
Vector toVector ()
Implemented in DataPoint.
Referenced by SVM.classify(), and SVM.computeSeparator().
The documentation for this interface was generated from the following file:
leImRo/src/leImRo/IDataPoint.java